//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class Gym_AccessoriesEntities : DbContext
{
    public Gym_AccessoriesEntities()
        : base("name=Gym_AccessoriesEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tblAdmin> tblAdmins { get; set; }
    public virtual DbSet<tblBrand> tblBrands { get; set; }
    public virtual DbSet<tblCategory> tblCategories { get; set; }
    public virtual DbSet<tblPro> tblProes { get; set; }
    public virtual DbSet<tblProduct> tblProducts { get; set; }
    public virtual DbSet<tblTemp> tblTemps { get; set; }
    public virtual DbSet<tblUser> tblUsers { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserType> UserTypes { get; set; }
    public virtual DbSet<tblOrderDetail> tblOrderDetails { get; set; }
    public virtual DbSet<tblOrderMain> tblOrderMains { get; set; }

    public virtual ObjectResult<adminLogin_Result> adminLogin(string email, string password)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        var passwordParameter = password != null ?
            new ObjectParameter("password", password) :
            new ObjectParameter("password", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<adminLogin_Result>("adminLogin", emailParameter, passwordParameter);
    }

    public virtual int deleteAdmin(Nullable<int> adminID)
    {
        var adminIDParameter = adminID.HasValue ?
            new ObjectParameter("adminID", adminID) :
            new ObjectParameter("adminID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteAdmin", adminIDParameter);
    }

    public virtual int deleteBrand(Nullable<int> brandID)
    {
        var brandIDParameter = brandID.HasValue ?
            new ObjectParameter("brandID", brandID) :
            new ObjectParameter("brandID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteBrand", brandIDParameter);
    }

    public virtual int deleteCategory(Nullable<int> iD)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteCategory", iDParameter);
    }

    public virtual int deleteProduct(Nullable<int> iD)
    {
        var iDParameter = iD.HasValue ?
            new ObjectParameter("ID", iD) :
            new ObjectParameter("ID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteProduct", iDParameter);
    }

    public virtual ObjectResult<listAdmins_Result> listAdmins()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listAdmins_Result>("listAdmins");
    }

    public virtual ObjectResult<productThrouPID_Result> productThrouPID(Nullable<int> productID)
    {
        var productIDParameter = productID.HasValue ?
            new ObjectParameter("productID", productID) :
            new ObjectParameter("productID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<productThrouPID_Result>("productThrouPID", productIDParameter);
    }

    public virtual ObjectResult<showBrandProduct_Result> showBrandProduct(Nullable<int> brandID)
    {
        var brandIDParameter = brandID.HasValue ?
            new ObjectParameter("brandID", brandID) :
            new ObjectParameter("brandID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showBrandProduct_Result>("showBrandProduct", brandIDParameter);
    }

    public virtual ObjectResult<showBrands_Result> showBrands()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showBrands_Result>("showBrands");
    }

    public virtual ObjectResult<showCategory_Result> showCategory()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showCategory_Result>("showCategory");
    }

    public virtual int showempolyTypes()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("showempolyTypes");
    }

    public virtual ObjectResult<showProductsWBC_Result> showProductsWBC()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showProductsWBC_Result>("showProductsWBC");
    }

    public virtual ObjectResult<showProWBrAndCat_Result> showProWBrAndCat(Nullable<int> catID, Nullable<int> brandID)
    {
        var catIDParameter = catID.HasValue ?
            new ObjectParameter("catID", catID) :
            new ObjectParameter("catID", typeof(int));

        var brandIDParameter = brandID.HasValue ?
            new ObjectParameter("brandID", brandID) :
            new ObjectParameter("brandID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showProWBrAndCat_Result>("showProWBrAndCat", catIDParameter, brandIDParameter);
    }

    public virtual ObjectResult<showProWithCat_Result> showProWithCat(Nullable<int> catID)
    {
        var catIDParameter = catID.HasValue ?
            new ObjectParameter("catID", catID) :
            new ObjectParameter("catID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showProWithCat_Result>("showProWithCat", catIDParameter);
    }

    public virtual ObjectResult<showUser_Result> showUser()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showUser_Result>("showUser");
    }

    public virtual ObjectResult<userLogin_Result> userLogin(string email, string password)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        var passwordParameter = password != null ?
            new ObjectParameter("password", password) :
            new ObjectParameter("password", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<userLogin_Result>("userLogin", emailParameter, passwordParameter);
    }

    public virtual ObjectResult<ViewCart_Result> ViewCart(string uniqueID)
    {
        var uniqueIDParameter = uniqueID != null ?
            new ObjectParameter("UniqueID", uniqueID) :
            new ObjectParameter("UniqueID", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewCart_Result>("ViewCart", uniqueIDParameter);
    }

    public virtual int deleteCartProduct(Nullable<int> productID)
    {
        var productIDParameter = productID.HasValue ?
            new ObjectParameter("ProductID", productID) :
            new ObjectParameter("ProductID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteCartProduct", productIDParameter);
    }
}
