//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblAdmin
{
    public int adminId { get; set; }
    public string adminName { get; set; }
    public string adminEmail { get; set; }
    public string adminPassword { get; set; }
    public bool status { get; set; }
}

public partial class tblBrand
{
    public tblBrand()
    {
        this.tblProducts = new HashSet<tblProduct>();
    }

    public int brandID { get; set; }
    public string brandName { get; set; }

    public virtual ICollection<tblProduct> tblProducts { get; set; }
}

public partial class tblCategory
{
    public tblCategory()
    {
        this.tblProducts = new HashSet<tblProduct>();
    }

    public int categoryID { get; set; }
    public string categoryName { get; set; }

    public virtual ICollection<tblProduct> tblProducts { get; set; }
}

public partial class tblOrderDetail
{
    public int OrderDetialID { get; set; }
    public int productID { get; set; }
    public Nullable<int> userID { get; set; }
    public decimal productPrice { get; set; }

    public virtual tblOrderMain tblOrderMain { get; set; }
}

public partial class tblOrderMain
{
    public tblOrderMain()
    {
        this.tblOrderDetails = new HashSet<tblOrderDetail>();
    }

    public int userID { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
    public string MobileNo { get; set; }
    public string EmailID { get; set; }
    public string ShippingAddress { get; set; }
    public decimal TotalAmount { get; set; }

    public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
}

public partial class tblPro
{
    public int productID { get; set; }
    public string productName { get; set; }
    public string productISBN { get; set; }
    public string productImage { get; set; }
}

public partial class tblProduct
{
    public int productID { get; set; }
    public string productName { get; set; }
    public string productModel { get; set; }
    public decimal productPrice { get; set; }
    public int categoryID { get; set; }
    public string productImage { get; set; }
    public int brandID { get; set; }

    public virtual tblBrand tblBrand { get; set; }
    public virtual tblCategory tblCategory { get; set; }
}

public partial class tblTemp
{
    public int tempID { get; set; }
    public int ProductIDD { get; set; }
    public string uniqueID { get; set; }
    public string currentDateAndTime { get; set; }
}

public partial class tblUser
{
    public int userID { get; set; }
    public string userName { get; set; }
    public string userEmail { get; set; }
    public string userPassword { get; set; }
    public bool status { get; set; }
}

public partial class User
{
    public int userID { get; set; }
    public string userFName { get; set; }
    public string userLName { get; set; }
    public string userEmail { get; set; }
    public bool userGender { get; set; }
    public int userType { get; set; }

    public virtual UserType UserType1 { get; set; }
}

public partial class UserType
{
    public UserType()
    {
        this.Users = new HashSet<User>();
    }

    public int userTypeID { get; set; }
    public string userType1 { get; set; }

    public virtual ICollection<User> Users { get; set; }
}

public partial class adminLogin_Result
{
    public int adminId { get; set; }
    public string adminName { get; set; }
    public string adminEmail { get; set; }
    public string adminPassword { get; set; }
    public bool status { get; set; }
}

public partial class listAdmins_Result
{
    public int adminId { get; set; }
    public string adminName { get; set; }
    public string adminEmail { get; set; }
    public string adminPassword { get; set; }
    public bool status { get; set; }
}

public partial class productThrouPID_Result
{
    public string productName { get; set; }
    public string productModel { get; set; }
    public decimal productPrice { get; set; }
    public string productImage { get; set; }
}

public partial class showBrandProduct_Result
{
    public int productID { get; set; }
    public string productName { get; set; }
    public string productModel { get; set; }
    public decimal productPrice { get; set; }
    public int categoryID { get; set; }
    public string productImage { get; set; }
    public int brandID { get; set; }
}

public partial class showBrands_Result
{
    public int brandID { get; set; }
    public string brandName { get; set; }
}

public partial class showCategory_Result
{
    public int categoryID { get; set; }
    public string categoryName { get; set; }
}

public partial class showProductsWBC_Result
{
    public int productID { get; set; }
    public string productName { get; set; }
    public string brandName { get; set; }
    public decimal productPrice { get; set; }
    public string productModel { get; set; }
    public string categoryName { get; set; }
    public string productImage { get; set; }
}

public partial class showProWBrAndCat_Result
{
    public int productID { get; set; }
    public string productName { get; set; }
    public string productModel { get; set; }
    public decimal productPrice { get; set; }
    public int categoryID { get; set; }
    public string productImage { get; set; }
    public int brandID { get; set; }
}

public partial class showProWithCat_Result
{
    public int productID { get; set; }
    public string productName { get; set; }
    public string productModel { get; set; }
    public decimal productPrice { get; set; }
    public int categoryID { get; set; }
    public string productImage { get; set; }
    public int brandID { get; set; }
}

public partial class showUser_Result
{
    public int userTypeID { get; set; }
    public string userType { get; set; }
}

public partial class userLogin_Result
{
    public int userID { get; set; }
    public string userName { get; set; }
    public string userEmail { get; set; }
    public string userPassword { get; set; }
    public bool status { get; set; }
}

public partial class ViewCart_Result
{
    public string productImage { get; set; }
    public string productName { get; set; }
    public string productModel { get; set; }
    public decimal productPrice { get; set; }
    public int productID { get; set; }
}
